language: node_js

node_js:
  - '8'

before_install:
- yarn install gulp -g

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  local-dir: ./docs
  fqdn: 'https://www.robertgabriel.ninja'
  edge:
    branch: v1.8.47
  on:
    branch: master
cache:
  yarn: true
  directories:
    - node_modules
script:
- yarn run start
