language: node_js

node_js:
  - '8'

before_install:
- npm install


deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  local-dir: ./dist
  fqdn: 'https://www.robertgabriel.ninja'
  on:
    branch: master

cache:
  npm: true
  directories:
    - node_modules

script:
- npm run start
